// <auto-generated />
namespace SntsepomexContributionLoader.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AdiciondeTipodeContribucion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdiciondeTipodeContribucion));
        
        string IMigrationMetadata.Id
        {
            get { return "201808132137060_Adicion de Tipo de Contribucion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
